{
 "title": "smartfleet-fleet overview Copy",
 "time": { "from": "2026-04-16T07:53:13.634Z", "to": "2026-04-16T08:13:13.634Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Vehicle Health Scores",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vehicle_health_score", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "Total Anomalies Detected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vehicle_anomaly_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vehicle_battery", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fuel Levels",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vehicle_fuel_level", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Vehicle Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "vehicle_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Engine Temperature °C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "expr": "vehicle_engine_temp", "legendFormat": "__auto" }
   ]
  }
 ]
}