from pydantic import BaseModel, Field
from typing import Literal


class TelemetryData(BaseModel):
    """Incoming sensor payload from each vehicle (posted every second)."""
    vehicle_id:  str
    engine_temp: float = Field(..., description="Engine temperature in °C")
    fuel_level:  float = Field(..., description="Fuel level as a percentage 0–100")
    speed:       float = Field(..., description="Speed in km/h")
    battery:     float = Field(..., description="Battery voltage in Volts")
    rpm:         float = Field(..., description="Engine RPM")


class Alert(BaseModel):
    """A single anomaly alert generated by the gateway."""
    vehicle_id: str
    message:    str
    severity:   Literal["WARNING", "ALERT", "CRITICAL"]
    timestamp:  float


class VehicleStatus(BaseModel):
    """Full status snapshot for one vehicle — returned by GET /vehicles."""
    vehicle_id:    str
    engine_temp:   float
    fuel_level:    float
    speed:         float
    battery:       float
    rpm:           float
    status:        Literal["OK", "WARNING", "CRITICAL"]
    health_score:  float
    timestamp:     float
    anomaly_count: int


class TelemetryResponse(BaseModel):
    """What the gateway returns after receiving a telemetry POST."""
    status:         str
    vehicle_status: Literal["OK", "WARNING", "CRITICAL"]
    health_score:   float
    alerts:         list[Alert]